# Data preprocessing

In [1]:
import pyreadr

# Read data from rds file
data = pyreadr.read_r('data/f1_dat.rds')
# Extract the df
df = data[None]
# Drop irrelevant columns 
df.drop(['round', 'circuit', 'weather_type', 'circuit_type', 'status'], axis=1, inplace=True)
# Select years 2017-2021
df = df[df['year'] >= 2017]
df.reset_index(drop=True, inplace=True)
# Unify constructor names
df = df.replace({'force_india': 'aston_martin',
                 'racing_point': 'aston_martin',
                 'toro_rosso': 'alphatauri',
                 'renault': 'alpine',
                 'sauber': 'alfa'})
# Change race positions range to 0-19
df['position'] -= 1
# Export data
df.to_csv('data/f1_results.csv', index=False)

df

              driver constructor  year  position
0             vettel     ferrari  2017         0
1           hamilton    mercedes  2017         1
2             bottas    mercedes  2017         2
3          raikkonen     ferrari  2017         3
4     max_verstappen    red_bull  2017         4
...              ...         ...   ...       ...
2015          latifi    williams  2021        15
2016      giovinazzi        alfa  2021        16
2017         russell    williams  2021        17
2018       raikkonen        alfa  2021        18
2019         mazepin        haas  2021        19

[2020 rows x 4 columns]